FROM amazoncorretto:21-al2023
ENV TZ=Asia/Shanghai
WORKDIR /app

RUN yum install -y wget xz tar && \
    yum clean all && \
    rm -rf /var/cache/yum
# 安装 ffmpeg
RUN wget --timeout=60 --tries=2 https://seechange.sgp1.digitaloceanspaces.com/ffmpeg-release-amd64-static.tar.xz && \
    tar -xf ffmpeg-release-amd64-static.tar.xz --strip-components=1 -C /usr/local/bin && \
    ln -sf /usr/local/bin/ffmpeg /usr/bin/ffmpeg && \
    rm -f ffmpeg-release-amd64-static.tar.xz

COPY target/*.jar app.jar
EXPOSE 9001
EXPOSE 9002
ENTRYPOINT ["java", "-jar", "app.jar"]